# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 巴扎嘿的博客
subtitle: a newbie's blog
description: a newbie's blog
author: wjExcceed
email: 

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: //
root: /
permalink: :year/:month/:day/:title/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
permalink_defaults:

# Directory
source_dir: source
public_dir: public

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
highlight:                                                                                                                                                                                                   
  enable: true                                                                                                                                                                                               
  auto_detect: true                                                                                                                                                                                          
  line_number: true                                                                                                                                                                                          
  tab_replace: ''

# Category & Tag
default_category: uncategorized
category_map:
    札记: diary
    编程: programming
    生活: life
    聚沙成塔: record
    
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 2
category: 2
tag: 2

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
server_ip: localhost
logger: false
logger_format: dev

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 8
pagination_dir: page

# Disqus
disqus_shortname:

# Extensions
## Plugins: https://github.com/hexojs/hexo/wiki/Plugins
## Themes: https://github.com/hexojs/hexo/wiki/Themes
 plugins:
  - hexo-generator-feed
  - hexo-generator-baidu-sitemap
  - hexo-generator-sitemap
  - hexo-generator-tag
  - hexo-generator-category
  - hexo-renderer-less
  - hexo-renderer-ejs
  - hexo-generator-index

theme: yelee
exclude_generator:

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://github.com/wjExcceed/wjExcceed.github.io
  branch: master

#deploy:
#  type: git
#  host: 120.24.181.238
#  user: root
#  root: /usr/local/nginx/litten.me/
#  port: 22

sitemap:
    path: sitemap.xml
baidusitemap:
    path: baidusitemap.xm

#RSS configuration:
feed:
    type: atom
    path: atom.xml
    limit: 100

#Search Engine Keywords    
keywords:
- Java
- MySQL
- concurrent
- IO
- Network
- Leetcode
- PAT
- Java Web
- iBatis
- Spring MVC
- Hibernate

jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: true
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: true
    tags: true

# set algolia configuration
algolia:
  appId: "JZ8RDKL1JY"
  apiKey: "a9a0fd8a6580215b0d121725788e39e8"
  adminApiKey: "30b9e4dd727b4e3052df7ce1d279206e"
  chunkSize: 5000
  indexName: "tranquilpeak"
fields:
    - title
    - date
    - permalink
    - thumbnailImageUrl
    - tags
    - categories
    - excerpt
    - excerpt:strip
